REM   Script: Major Assignment -2
REM   Major Assignment -2 SQL

CREATE TABLE STATION 
(ID NUMBER PRIMARY KEY, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N NUMBER, 
LONG_W NUMBER);

 INSERT INTO STATION VALUES (13, 'Phoenix', 'AZ', 33, 112);

INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);

INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

SELECT * FROM STATION;

SELECT * FROM STATION 
WHERE LAT_N > 39.7;

CREATE TABLE STATS 
(ID NUMBER REFERENCES STATION(ID), 
MONTH NUMBER CHECK (MONTH BETWEEN 1 AND 12), 
TEMP_F NUMBER CHECK (TEMP_F BETWEEN -80 AND 150), 
RAIN_I NUMBER CHECK (RAIN_I BETWEEN 0 AND 100), 
PRIMARY KEY (ID, MONTH));

INSERT INTO STATS VALUES (13, 1, 57.4, 0.31);

INSERT INTO STATS VALUES (13, 7, 91.7, 5.15);

INSERT INTO STATS VALUES (44, 1, 27.3, 0.18);

INSERT INTO STATS VALUES (44, 7, 74.8, 2.11);

INSERT INTO STATS VALUES (66, 1, 6.7, 2.10);

INSERT INTO STATS VALUES (66, 7, 65.8, 4.52);

SELECT * FROM STATION, STATS 
WHERE STATION.ID = STATS.ID;

SELECT MONTH, ID, RAIN_I, TEMP_F FROM STATS 
CITY FROM STATION 
ORDER BY MONTH, RAIN_I DESC 
WHERE STATION.ID = STATS.ID;

SELECT * FROM STATS, STATION 
ORDER BY MONTH, RAIN_I DESC, 
WHERE STATS.ID=STATION.ID;

SELECT MONTH, ID, RAIN_I, TEMP_F 
FROM STATS 
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
ORDER BY MONTH, RAIN_I DESC 
  WHERE STATION.ID=STATS.ID ;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
ORDER BY MONTH, RAIN_I DESC 
WHERE STATION.ID=STATS.ID ;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
  WHERE STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC ;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
WHERE STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
LEFT JOINS STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
LEFT JOIN STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
LEFT JOIN ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
LEFT JOIN STATION ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
RIGHT JOIN STATION ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, ID, RAIN_I, TEMP_F 
FROM STATION, STATS 
INNER JOIN STATION ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT  MONTH, ID, RAIN_I, TEMP_F 
FROM STATS 
INNER JOIN CITY ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY 
FROM STATION 
INNER JOIN STATS ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, RAIN_I, TEMP_F 
FROM STATION 
  ORDER BY MONTH, RAIN_I DESC 
INNER JOIN STATS ON STATION.ID=STATS.ID  ;

SELECT CITY, MONTH, RAIN_I, TEMP_F 
FROM STATION 
  ORDER BY MONTH, RAIN_I DESC 
INNER JOIN STATS ON STATION.ID=STATS.ID ;

SELECT CITY, MONTH, RAIN_I, TEMP_F, 
FROM STATION 
  ORDER BY MONTH, RAIN_I DESC 
INNER JOIN STATS ON STATION.ID=STATS.ID ;

SELECT CITY, MONTH, RAIN_I, TEMP_F, 
FROM STATION, STATS 
  ORDER BY MONTH, RAIN_I DESC 
INNER JOIN STATS ON STATION.ID=STATS.ID ;

SELECT CITY, MONTH, RAIN_I, TEMP_F, 
FROM STATION, STATS 
ORDER BY MONTH, RAIN_I DESC 
INNER JOIN STATS ON STATION.ID=STATS.ID ;

SELECT CITY, MONTH, RAIN_I, TEMP_F, 
FROM STATION, STATS 
ORDER BY MONTH, RAIN_I DESC 
SELF JOIN STATS ON STATION.ID=STATS.ID ;

SELECT LAT_N, CITY, TEMP_F 
FROM STATS, STATION 
WHERE MONTH = 7 
AND STATS.ID = STATION.ID 
ORDER BY TEMP_F;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID 
FROM STATS 
GROUP BY ID;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID 
FROM STATS 
GROUP BY CITY;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
GROUP BY ID;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
GROUP BY ID 
   WHERE STATS.ID=STATION.ID;

UPDATE STATS SET RAIN_I = RAIN_I + 0.01;

UPDATE STATS SET TEMP_F = 74.9 
WHERE ID = 44 
AND MONTH = 7;

SELECT CITY, MONTH, RAIN_I, TEMP_F, 
FROM STATION, STATS 
JOIN STATS ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT CITY, MONTH, RAIN_I, TEMP_F, 
FROM STATION, STATS 
JOIN STATS  
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, 
FROM STATS 
JOIN STATATION 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC, CITY;

SELECT MONTH, RAIN_I, TEMP_F, 
FROM STATS 
JOIN STATATION 
ON STATION.CITY=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, 
FROM STATS 
JOIN STATATION 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, 
FROM STATS 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS 
LEFT JOIN STATION ORDERED BY CITY, 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS 
LEFT JOIN STATION  
ORDER BY CITY, 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS 
LEFT JOIN STATION  
WHERE CITY, 
ON STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS 
LEFT JOIN STATION  
WHERE STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS, STATION 
LEFT JOIN STATION  
WHERE STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT MONTH, RAIN_I, TEMP_F, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID  
ORDER BY MONTH, RAIN_I DESC;

SELECT * FROM STATS;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
GROUP BY ID 
WHERE STATS.ID=STATION.ID;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATS.ID=STATION.ID;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
LEFT JOIN STATS.ID=STATION.ID;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
RIGHT JOIN STATS.ID=STATION.ID;

 SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATS.ID=STATION.ID 
ORDER BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
ORDER BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
ORDER BY TEMP_F DESC;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, 
  WHERE STATION.ID=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS 
  WHERE STATION.ID=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STARION 
WHERE STATION.ID=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.CITY=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
GROUP BY CITY;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
GROUP BY ID ;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID, CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), CITY 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID 
FROM STATS, STATION 
WHERE STATION.ID=STATS.ID 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), CITY 
FROM STATS, STATION 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID 
FROM STATS, STATION 
GROUP BY ID;

SELECT MAX(TEMP_F), MIN(TEMP_F), AVG(RAIN_I), ID 
FROM STATS 
GROUP BY ID;

CREATE VIEW METRIC_STATS (ID, MONTH, TEMP_C, RAIN_C) AS 
SELECT ID, 
MONTH, 
(TEMP_F - 32) * 5 /9, 
RAIN_I * 2.54, 
FROM STATS;

CREATE VIEW METRIC_STATS (ID, MONTH, TEMP_C, RAIN_C) AS 
SELECT ID, 
MONTH, 
(TEMP_F - 32) * 5 /9, 
RAIN_I * 0.3937 
FROM STATS;

SELECT * FROM METRIC_STATS;

